services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: porfolio-frontend
    restart: unless-stopped
    ports:
      - '8081:80'
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
